### ISSUE TITLE
command and windows start behaviour

### ISSUE THREAD

**Issue by Alexander-van-aken** [stroebjo/autohotkey-windows-mac-keyboard#11]
How whould you suggest working with releasing a windows button. I use CMD+Q to quit etc, but sometimes I just press windows key without doing anything. Is there a way to block the windows start menu but keep the function of it like CMD+Q etc.

**Comment by stroebjo** [comment]
Sorry, I don't have an idea for that. I think the AHK forums are a better place to find a solution for this: https://autohotkey.com/boards/
