### ISSUE TITLE
Cut/Copy/Paste, New Tab - not working Win 10

### ISSUE THREAD

**Issue by BinaryShrub** [stroebjo/autohotkey-windows-mac-keyboard#12]
I got around it by adding `Send,`

```
; Selecting
#a::Send, ^a

; Copying
#c::Send, ^c

; Pasting
#v::Send, ^v

; Cutting
#x::Send, ^x
```

**Comment by nsimeonov** [comment]
Thank you
Thank you
Thank you

**Comment by nsimeonov** [comment]
One small detail - if one runs an application as administrator (like I have to do with Visual Studio when debugging an IIS process), then you have to run the script as administrator as well:

https://stackoverflow.com/questions/1890351/why-is-visual-studio-catching-key-events-before-autohotkey

**Comment by sangregoriopaolo** [comment]
This is the correct soultion, it should be merged in @stroebjo :)

**Comment by renatosc** [comment]
@BinaryShrub solution worked for me.

**Comment by KJBurnett** [comment]
Is there a reason this fix has not been merged into master?
@stroebjo @BinaryShrub 

Thanks!

**Comment by stroebjo** [comment]
Finally added! Thanks for the fix!
