### ISSUE TITLE
AltTab cycle backwards?

### ISSUE THREAD

**Issue by marhoy** [stroebjo/autohotkey-windows-mac-keyboard#19]
I just started using AHK since I've got a Mac keyboard (Logitech MX Keys for Mac) that I'm using with a Windows laptop. I'm really glad I found this AHK-script, since it solves most of my issues.

One thing I find myself missing though, is the possibility to cycle backwards through the open windows using Shift + LeftCommand (LeftWin?)  + Tab.

It's really useful when you AltTab through your open windows and you go a little bit too far. Instead of cycling through all of them again, you just press Shift in addition (to modify the behavior of AltTab) and back up a few windows.

I've tried to create a mapping for this, but as I'm a total newbie on AHK-scripting, I'm lost...

**Comment by stroebjo** [comment]
At the moment I don't use a windows PC, so I can't support you in that regard. Sorry! But that sounds like a really good idea. Maybe you can find help in AHK forums? https://www.autohotkey.com/boards/

In case you get it to work, I'm happy to merge an PR!
