### ISSUE TITLE
AutoHotKey v1 is depricated

### ISSUE THREAD

**Issue by M1sterPl0w** [stroebjo/autohotkey-windows-mac-keyboard#21]
Like the title: AutoHotKey v1 is depricated :)

**Comment by stroebjo** [comment]
I'm no longer a daily user of AHK so I won't be able to produce an update to v2. But I'm happy to merge a PR / link to a fork with an update.

**Comment by M1sterPl0w** [comment]
Thanks for your response! And glad to hear you will merge a PR. When I find the time, I'll see if I can manage to update it to v2.
