### ISSUE TITLE
Remapping Command <-> Option (Windows <-> Alt) doesn't work with Ctrl+Alt+Delete

### ISSUE THREAD

**Issue by wnajar** [stroebjo/autohotkey-windows-mac-keyboard#4]
The following mapping:

```
LWin::LAlt
LAlt::LWin
```

Works to swap those two keys, but doesn't work for the `Ctrl+Alt+Delete` combo. Any idea why?

**Comment by stroebjo** [comment]
Sorry, no idea. Maybe you try to debug with the `Key history and Script info` utility and [run the task manager directly](https://autohotkey.com/board/topic/41582-ctrl-alt-del-replacement/?p=259494) with bindings AHK registers after the remapping?
