### ISSUE TITLE
F20 Key (Eject) binding not working

### ISSUE THREAD

**Issue by EpicLPer** [stroebjo/autohotkey-windows-mac-keyboard#5]
F20 is not recognized by AutoHotKey it seems, at least not on Windows 10. Even the tiny "ScanCode" application I found online which shows every key code doesn't react to the Eject key, meaning its not even recognized by the OS.

**Comment by stroebjo** [comment]
I checked with the `Key history and script info` utility inside AHK and a keypress of Eject doesn't seem to register. This is probably a issue with AHK itself then? I will add an comment in the code to alert about this issue, but I don't know how to provide a fix/if this can be fixed.
