### ISSUE TITLE
Pressing Ctrl/Shift/Alt + any scritped key doesn't work

### ISSUE THREAD

**Issue by EpicLPer** [stroebjo/autohotkey-windows-mac-keyboard#6]
The way the current script is built up doesn't allow for other buttons being pressed simultaneously, as example the Screenshot program I heavily use at work (FastStone Capture) is triggered with the Print key. Pressing it once makes a full screenshot, holding Shift/Ctrl either a triangular section or a window. However, while holding Ctrl or Shift the Print-Key isn't registered anymore.

**Comment by stroebjo** [comment]
I'm not sure how this can be done, but I'm open to pull request if you figure it out. 

Maybe you can catch the input with the Function key directly and set to the app. Something like `+F13::Send {Shift}{PrintScreen}` maybe.
