### ISSUE TITLE
handle ShiftAltTab

### ISSUE THREAD

**Issue by holiber** [stroebjo/autohotkey-windows-mac-keyboard#7]
Hey. Very helpful repo! I see `AltTab` handler but what about `ShiftAltTab`?

**Comment by stroebjo** [comment]
Hey,

awesome that the code helps you! 

What do you mean with `ShiftAltTab`? For window switching `Shift` seems to work, to reverse the direction.

Sorry, at the moment I don't use the script actively, so I'm not quite sure. If you want to add a feature, I'm happy to merge a Pull Request! :)
